include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
  errors:
    avoid_print: error

linter:
  rules:
    always_declare_return_types: true
    prefer_final_locals: true
    use_super_parameters: true

